### ISSUE TITLE
sh: 1: heroku: not found

### ISSUE THREAD

**Issue by venorme** [KMarshland/heroku-ssl#1]
Getting this error while running heroku run rake heroku_ssl:update_certs --app myapp
it starts - Once your app has been deployed to Heroku, hit enter.
than asks for email (can you pls clarify which one)
Than goes:
sh: 1: heroku: not found
rake aborted!
NoMethodError: undefined method `map!' for nil:NilClass
/app/vendor/bundle/ruby/2.2.0/gems/heroku_ssl-0.6.1/lib/tasks/heroku_ssl_tasks.rake:102:in `get_domains'
/app/vendor/bundle/ruby/2.2.0/gems/heroku_ssl-0.6.1/lib/tasks/heroku_ssl_tasks.rake:10:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/cli/exec.rb:27:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:332:in `exec'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:20:in `dispatch'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/cli.rb:11:in `start'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/exe/bundle:34:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/lib/bundler/friendly_errors.rb:100:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.2.0/gems/bundler-1.13.6/exe/bundle:26:in `<top (required)>'
/app/bin/bundle:3:in `load'
/app/bin/bundle:3:in `<main>'

Cant understand whats the problem and if its on my side

**Comment by KMarshland** [comment]
I suspect that you do not have the heroku toolbelt installed: [https://devcenter.heroku.com/articles/heroku-cli](https://devcenter.heroku.com/articles/heroku-cli). Run `heroku --version` to verify that you have it.

I'll update the readme and push a fix so that it fails more gracefully.

**Comment by venorme** [comment]
Thanks for answer.
I am using toolbelt to push to heroku - version 3.43.16.
Will try to reinstall it - but we have tried running rake task using few computers - its unlikely they all have toolbelt issues/

**Comment by KMarshland** [comment]
What operating system are you using, and are you using rvm, rbenv, or something else?
