### ISSUE TITLE
Reissuing

### ISSUE THREAD

**Issue by toobulkeh** [KMarshland/heroku-ssl#3]
This looks like a cool gem!

Currently, we're using [Sabayon](https://github.com/dmathieu/sabayon), which provides a separate app and requires an API key to modify Heroku's ENV variables.

I like your approach of using Redis, a free service, attached to each app instead, as it definitely cuts down and would actually be automatable.

Have you looked at making the process reissuable through a heroku cron task that runs daily?
Lets Encrypt suggest reissuing certs if they're expiring soon.

I'd be happy to switch over if this had re-issue support. I'd also be happy to contribute that support.

**Comment by KMarshland** [comment]
I have looked into this -- the main issue is uploading the certificates on your behalf. That is, this gem could very easily get fresh certificates when needed; the problem is it can't upload them to heroku because:
- The heroku toolbelt isn't installed by default with the standard rails buildpack, meaning it couldn't run `heroku certs:update`. The solution would be to use this gem: https://github.com/heroku/platform-api
- It would need authorization. The solution here would be to use the heroku-oauth toolbelt plugin. 

If you'd like to work on how to change these, I'd be thrilled to merge a PR.

**Comment by toobulkeh** [comment]
How does this gem currently upload certificates?

**Comment by KMarshland** [comment]
It simply runs `heroku certs:update`, which makes use of the same authorization that lets you run something like `heroku run rails c` manually.

https://github.com/KMarshland/heroku-ssl/blob/master/lib/tasks/heroku_ssl_tasks.rake#L78-L82

**Comment by toobulkeh** [comment]
Ah, so locally and manually -- my misunderstanding.

I like the Sabayon approach, but it requires a manual process of getting an API key -- which Heroku doesn't specify permissions at this point.

**Comment by KMarshland** [comment]
Yeah. One option would be to just write a cron job locally (or on an arbitrary linux box somewhere) that has authorization. 

My current plans are to work on making this gem more configurable, then write an idempotent rake task to renew certificates close to expiry. At that point it should be pretty straightforward to set up either a local cron job or API authorization to run it through the heroku scheduler.

**Comment by toobulkeh** [comment]
Makes sense. Here's the [approach from Sabayon](https://github.com/dmathieu/sabayon/blob/master/cmd/sabayon/main.go#L52) on doing it a month beforehand, which aligns with LetsEncrypt's suggestions.

**Comment by dijonkitchen** [comment]
In the [certbot docs](https://certbot.eff.org/docs/using.html#renewal), it says to run it twice a day since the renewal only happens when it's within 1 month of expiring. That way, it'll be able to renew in case there's an error.

**Comment by toobulkeh** [comment]
@KMarshland -- heads up -- Heroku now does this automatically. https://devcenter.heroku.com/articles/automated-certificate-management
